IDEAS = [
  "This web app. Yes, the one you're using right now.",
  "A yuppie baby name generator",
  "A yuppie baby name generator ... IN THE CLOUD",
  %q{A service that adds any text to any image. Like this image <a href="http://memecaptain.com/i?u=http://images5.fanpop.com/image/photos/24800000/Hufflepuff-backpack-lifesgoodx3-24857969-500-500.jpg&tt=ERRYDAY+I'M&tb=PUFFLIN">right here</a>.},
  "A human year &harr; dog year calculator",
  "A to-do list",
  "A to-do list ... IN THE CLOUD",
  "Mad Libs!",
  "A choose-your-own adventure game",
  "A guess-what-number-I'm-thinking-of game",
  # "A service that tells you if that's what she said. It's not that hard. (That's what she said.)",
  # "An anagram generator.",
  # %q{A little app to manipulate photos, <a href="http://camanjs.com/#example-table">like this</a>. You can build something awesome for <a href="http://www.photohackday.org/about.html">Photo Hack Day</a>!}
  "An app that asks for two numbers and adds them",
  "An app that asks for two numbers and subtracts them",
  "An app that asks for the lengths of two sides of a right triangle and displays the length of the hypotenuse",
  "A coin-toss program (heads ... or tails?!?!?!?!)",
  "An app that asks for your first and last name and display your full name",
  "Rock paper scissors",
  "A dice roller",
  "An app that Snoop Doggifies every word.",
  "A palindrome detector",
  "Tic tac toe",
  "Guess the word (Treat yo' _ _ _ _)"
]
