IDEAS = [
  "A yuppie baby name generator",
  "A yuppie baby name generator ... IN THE CLOUD",
  "A human year &harr; dog year calculator",
  "A to-do list",
  "A to-do list ... IN THE CLOUD",
  "Mad Libs!",
  "A choose-your-own adventure game",
  "A guess-what-number-I'm-thinking-of game",
  "An app that asks for two numbers and adds them",
  "An app that asks for two numbers and subtracts them",
  "An app that asks for the lengths of two sides of a right triangle and displays the length of the hypotenuse",
  "A coin-toss program: heads ... or tails?!?!?!?!",
  "An app that asks for your first and last name and display your full name",
  "Rock paper scissors",
  "A dice roller",
  "An app that Snoop Doggifies every wordizzle",
  "Tic tac toe",
  "Guess the word: Treat yo' _ _ _ _",
  "Number to roman numeral converter",
  "How old will you be in 2016? How old were you in 1998?",
  "A fortune-teller that tells different people different fortunes",
  "Print out the lyrics to 99 bottles of beer",
  %q{<a href="http://pine.fm/LearnToProgram/?Chapter=06">Deaf Grandma program</a>},
]
